### PR TITLE
fix sql insert column function, change the way to insert a new row

### PR DESCRIPTION
**Pull request by lijinyang0228**
This change is [Reviewable](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/17)

### CODE REVIEW

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 567 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/17#-M4pAZ85D_zLJ6tuJi7N:-M4qrDR98P_ASOSveis1:bb64b7t) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/b97d7046374d58368d1708757508e026ae0c82a0/pkg/routes/routes.go#L567)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

When we choose the max index maintained by the sql connection, I guess this won't work if the database changes are made not by dataspread. Shouldn't this be select max(colmap[idcolumnindex].type.string) from db.table? And is there a way to insert a row at a specific position currently? Didn't lauren use an insert row function that took in an index?
</blockquote></details>

ah I didn’t consider the case a table is changed not by dataspread.
Yes insertrow function should take in an index
I'll change it in the next PR

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 493 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/17#-M4p9uYE8fo-rCzmP3Ov:-M4qrw0e8WFEL_Msn5UC:b64d5iv) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/b97d7046374d58368d1708757508e026ae0c82a0/pkg/routes/routes.go#L493)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

comment
</blockquote></details>

will delete it

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 567 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/17#-M4pAZ85D_zLJ6tuJi7N:-M4qsDCw-ZIY2Eq88kS8:b-cfu8t7) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/b97d7046374d58368d1708757508e026ae0c82a0/pkg/routes/routes.go#L567)):*
<details><summary><i>Previously, lijinyang0228 (Jinyang Li) wrote…</i></summary><blockquote>

ah I didn’t consider the case a table is changed not by dataspread.
Yes insertrow function should take in an index
I'll change it in the next PR
</blockquote></details>

Oh no I think InsertRow function should only take in cells that are already well structured. 
So we should call a function to query the max index and decide the ID for the new row, before calling InsertRow
Because I want to use sql.NullString type for cells, and before inserting, we should know whether a cell is null

**Comment by MinhyukPark** [comment]
___
*[pkg/routes/routes.go, line 567 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/17#-M4pAZ85D_zLJ6tuJi7N:-M4u7CEM1At4FEIZlKc7:b-oy4maz) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/b97d7046374d58368d1708757508e026ae0c82a0/pkg/routes/routes.go#L567)):*
<details><summary><i>Previously, lijinyang0228 (Jinyang Li) wrote…</i></summary><blockquote>

Oh no I think InsertRow function should only take in cells that are already well structured. 
So we should call a function to query the max index and decide the ID for the new row, before calling InsertRow
Because I want to use sql.NullString type for cells, and before inserting, we should know whether a cell is null
</blockquote></details>

oh hmm that sounds ok. So are you saying the insert row should take as input the max index?

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 567 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/17#-M4pAZ85D_zLJ6tuJi7N:-M4xZpeE82QlGQsTsQj5:b-q3fgxe) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/b97d7046374d58368d1708757508e026ae0c82a0/pkg/routes/routes.go#L567)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

oh hmm that sounds ok. So are you saying the insert row should take as input the max index?
</blockquote></details>

no, I think when calling InsertRow(), we should have all values of the new row ready, including the index. I mean index are treated the same as other values in the row, so we don't have an input for index in the function parameters.

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 489 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/17#-M4p9tjeBc69_XmEIDBD:-M4xaUeq75yDdJRt5vf6:b-896fix) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/b97d7046374d58368d1708757508e026ae0c82a0/pkg/routes/routes.go#L489)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

comment
</blockquote></details>

Done.

**Comment by lijinyang0228** [comment]
you can review differences between the latest version and the original one. Only Insert column is changed

**Pull request merged**
