### PR TITLE
Mysql prepare reuse

### PR DESCRIPTION
**Pull request by lijinyang0228**
This change is [Reviewable](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12)

### CODE REVIEW

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 5 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JGBgE5N4mXL_bAWyq:-M3Jcj8J16HN4lNy4dTu:b-7e5lve) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L5)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

these should be imported like the lines you commented out like github.com/MinhyukPark/dataspreadbackend/pkg/payload. You can't import it like that right now because it's not in master but we'll have to change it to the proper import statement once we can merge.
</blockquote></details>

I'll change it to "github.com/MinhyukPark/xxxxx", but I still don't understand. "../routes" refers to what the routes looks like in this branch, it doesn't affect master. "github.com/MinhyukPark/dataspreadbackend/pkg/routes" is routes in the master. 
Suppose I add a new function in routes, and use this function in webserver. If I import routes in master, webserver will report errors because master routes doesn't have the new function.

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 12 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JG1G65zvMO4FgNJPH:-M3Jf-BA8VNB15y40lWu:b4er6wr) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L12)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

make sure to not change the import order. You can run golint and gofmt to check for these errors.
</blockquote></details>

ok. I'll change it back

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 86 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JHC-w7VaxGuAZ7oVl:-M3JfHan87LfwAHdj4Bj:byikyod) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L86)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

shouldn't these be passed in from the body or the header of the request?
</blockquote></details>

This is what I'm not sure about. Should these be maintained in the workbench or frontend?

**Comment by lijinyang0228** [comment]
Oh I used it to test whether the sqlinterface is used correctly. I added it to git by mistake. I'll remove it

**Comment by lijinyang0228** [comment]
ok. I have deleted it

**Comment by MinhyukPark** [comment]
___
*[pkg/routes/routes.go, line 5 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JGBgE5N4mXL_bAWyq:-M3YbG353OZQ4q8Elz53:b-d2wuam) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L5)):*
<details><summary><i>Previously, lijinyang0228 (Jinyang Li) wrote…</i></summary><blockquote>

I'll change it to "github.com/MinhyukPark/xxxxx", but I still don't understand. "../routes" refers to what the routes looks like in this branch, it doesn't affect master. "github.com/MinhyukPark/dataspreadbackend/pkg/routes" is routes in the master. 
Suppose I add a new function in routes, and use this function in webserver. If I import routes in master, webserver will report errors because master routes doesn't have the new function.
</blockquote></details>

I think you said you figured it out but just to explain again, "we'll have to change it to the proper import statement once we can merge". You're right and we'll have to change it before you merge.

**Comment by MinhyukPark** [comment]
___
*[pkg/routes/routes.go, line 24 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3KXWlR9l6sYPfvU6Os:-M3YbXO94SjKqYDPjj0T:b-qtpvqx) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L24)):*
<details><summary><i>Previously, lijinyang0228 (Jinyang Li) wrote…</i></summary><blockquote>

> ```
> var _, _ = fmt.Println(nil)
> ```
What is this line used for?
</blockquote></details>

It's in the style doc but in Golang if a package isn't used but is imported it will throw an error. So we import but throw out the values.

**Comment by MinhyukPark** [comment]
___
*[pkg/routes/routes.go, line 86 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JHC-w7VaxGuAZ7oVl:-M3Yber0DIixWO8pkXeY:b9pp24y) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L86)):*
<details><summary><i>Previously, lijinyang0228 (Jinyang Li) wrote…</i></summary><blockquote>

This is what I'm not sure about. Should these be maintained in the workbench or frontend?
</blockquote></details>

I think we also talked about this over slack but just for documentation purposes, why can't we create the db from the request body? we already pass it in? Look at the head for these changes and it might make more sense?

**Comment by MinhyukPark** [comment]
___
*[pkg/routes/routes.go, line 95 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JHG1j2EdcmVkhSNC1:-M3YbxyM9D6a_QeF_0nV:btdt3lf) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L95)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

same for these as above.
</blockquote></details>

The query mult statement should be stored in the backend and the backend should find whichever is the correct statement to use by looking at the request headers right? Where are the insert statements stored correctly?

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 24 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3KXWlR9l6sYPfvU6Os:-M3nqUWr2ufi2GA-Vobg:bb7oryy) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L24)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

It's in the style doc but in Golang if a package isn't used but is imported it will throw an error. So we import but throw out the values.
</blockquote></details>

sure

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 5 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JGBgE5N4mXL_bAWyq:-M3nqW1z7wISVG8KBh8r:bb7oryy) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L5)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

I think you said you figured it out but just to explain again, "we'll have to change it to the proper import statement once we can merge". You're right and we'll have to change it before you merge.
</blockquote></details>

sure

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 86 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JHC-w7VaxGuAZ7oVl:-M3nr1YE7Nbso7_bTGh1:br65g1z) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L86)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

I think we also talked about this over slack but just for documentation purposes, why can't we create the db from the request body? we already pass it in? Look at the head for these changes and it might make more sense?
</blockquote></details>

yes I have made changes in the new PR

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 95 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JHG1j2EdcmVkhSNC1:-M3nrEy8CGn9Q0GvjL19:b9jko9v) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L95)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

The query mult statement should be stored in the backend and the backend should find whichever is the correct statement to use by looking at the request headers right? Where are the insert statements stored correctly?
</blockquote></details>

In the new PR, there is a map to store these statements

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 335 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JHbPIBG-deqfXN3TU:-M3ns2c4B31l0L2-w-v_:bb7f2mf) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L335)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

comment still here
</blockquote></details>

done

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 115 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JHNLK4ZfTxlbOmNMY:-M3nsAUW4lE4Fv0i0QgO:b-sqew7) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L115)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

and these.
</blockquote></details>

stored in map

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 242 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JHPCRC_bJyslqpyF3:-M3nsEAR8TwuC48g5lGr:b-sqew7) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L242)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

and these.
</blockquote></details>

stored in map

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 425 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JHsVo8q0AuchxpaCx:-M3nsGKEBbiE6bpeHI5N:b-sqew7) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L425)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

and these
</blockquote></details>

stored in map

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 447 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JHuRF8H7NQJ9TGxeM:-M3nsHrd2jb1tvLJGAdS:b-sqew7) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/routes/routes.go#L447)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

and these
</blockquote></details>

stored in map

**Comment by lijinyang0228** [comment]
___
*[pkg/webserver/webserver.go, line 13 at r1](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M3JHyNQ-yx0Drxqj6k4:-M3nsVCeAsbnEffXlpbR:b-2a7qdn) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/71a881341d9cc821ad0d4602ff8cbe1edf5be2ac/pkg/webserver/webserver.go#L13)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

imports reorder still
</blockquote></details>

Now, the last 4 imports are in the same order as the initial status. Not sure about the two new imports "fmt" and "payload".

**Comment by lijinyang0228** [comment]
This branch is based on old version master branch. I find it hard to write and run in this way due to some missing functionalists like add database. So I made changes based on the current master branch, run the system. And then I copy the codes into this branch to make the new PR. 
This is a little weird, and do you think I should make another branch from the current master, and copy codes into that one?

I use a map to store statements and find proper statements to execute. I have tried basic operations including insertrow, deleterow, updaterow. 

As for formulas, I didn't make any logical changes. I only changed the way of sql query in those formula functions.

I find sometimes the program writes into file index---, (indexFile := "index" + "-" + databaseData.SQLDatabase + "-" + databaseData.SQLTable + "-" + databaseData.SQLUser + ".csv"), and this happens every time I logout. Do you have any ideas why this would happen?

**Comment by MinhyukPark** [comment]
___
*[pkg/routes/routes.go, line 484 at r3](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M42HBaE7GVLC52pGLpb:-M42HBaE7GVLC52pGLpc:b-vh87mx) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/e4e21a46882a5053f8fe96498f393ae186d96f12/pkg/routes/routes.go#L484)):*
> ```Go
> 	sqlConn := SQLConn[utils.SqlinterfaceDBToString(db)]
> 	sqlConn.CloseStmt()
> 	indexFile := "index" + "-" + databaseData.SQLDatabase + "-" + databaseData.SQLTable + "-" + databaseData.SQLUser + ".csv"
> ```

isn't it because of here that logout triggers a indexFile write?

**Comment by MinhyukPark** [comment]
___
*[pkg/webserver/webserver.go, line 6 at r3](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M42I1LE5qiP7TgZFg3b:-M42I1LE5qiP7TgZFg3c:b-rk6mtp) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/e4e21a46882a5053f8fe96498f393ae186d96f12/pkg/webserver/webserver.go#L6)):*
> ```Go
> import (
> 	"fmt"
> 	"github.com/MinhyukPark/dataspreadbackend/pkg/payload"
> ```

custom imports like github.com/ imports should be in the second section. the first section should just be the native imports like fmt

**Comment by lijinyang0228** [comment]
___
*[pkg/webserver/webserver.go, line 6 at r3](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M42I1LE5qiP7TgZFg3b:-M489T-AEutK5Vitm2GA:b-exx3hi) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/e4e21a46882a5053f8fe96498f393ae186d96f12/pkg/webserver/webserver.go#L6)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

custom imports like github.com/ imports should be in the second section. the first section should just be the native imports like fmt
</blockquote></details>

I've fixed this in a new PR.

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 484 at r3](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M42HBaE7GVLC52pGLpb:-M48bi83Az05f8lYFxPl:b-jbvikv) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/e4e21a46882a5053f8fe96498f393ae186d96f12/pkg/routes/routes.go#L484)):*
<details><summary><i>Previously, MinhyukPark (Minhyuk Park) wrote…</i></summary><blockquote>

isn't it because of here that logout triggers a indexFile write?
</blockquote></details>

Yes and in this function, databaseData is supposed to be SQLHost, SQLPort, SQLType .... 
so indexFile will be index-dataspread_local-demo-dataspread-user-1
However, when I click logout, the databaseData is { } (empty)
and cannot get the correct indexFile.
I'm confused why this would happen

**Comment by lijinyang0228** [comment]
Yes I have fixed the import order. The only question remaining to solve is why logout request doesn't send sql info in its header.

**Comment by lijinyang0228** [comment]
___
*[pkg/routes/routes.go, line 484 at r3](https://reviewable.io/reviews/minhyukpark/dataspreadbackend/12#-M42HBaE7GVLC52pGLpb:-M48r1SH5BpZGXGm-u21:b-n4isa5) ([raw file](https://github.com/minhyukpark/dataspreadbackend/blob/e4e21a46882a5053f8fe96498f393ae186d96f12/pkg/routes/routes.go#L484)):*
<details><summary><i>Previously, lijinyang0228 (Jinyang Li) wrote…</i></summary><blockquote>

Yes and in this function, databaseData is supposed to be SQLHost, SQLPort, SQLType .... 
so indexFile will be index-dataspread_local-demo-dataspread-user-1
However, when I click logout, the databaseData is { } (empty)
and cannot get the correct indexFile.
I'm confused why this would happen
</blockquote></details>

I tried in master (both frontend and backend set to master) and when I click logout, the output info in the backend shows that databaseData is {      }. so indexFile = "index---"

**Comment by MinhyukPark** [comment]
So this PR is obsolete now right?

**Comment by lijinyang0228** [comment]
yes, it's obsolete

**Comment by MinhyukPark** [comment]
closing since it's obsolete.

**Pull request closed without merging**
